In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data=pd.read_csv('creditcard.csv')

In [3]:
credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
legil=credit_card_data[credit_card_data.Class==0]
fruad=credit_card_data[credit_card_data.Class==1]

In [31]:
print(legil.shape)
print(fruad.shape)

(284315, 31)
(492, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [9]:
new_legit=legil.sample(n=492)

In [10]:
new_data=pd.concat([new_legit,fruad],axis=0)

In [11]:
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
4109,3742.0,1.296273,-0.602021,0.615666,-0.466158,-1.047252,-0.563438,-0.783412,-0.051961,0.756842,...,-0.215915,-0.624529,0.165192,-0.057929,0.063396,-0.488104,-0.017801,0.015398,44.50,0
258626,158744.0,2.011600,-0.185795,-1.029954,0.334180,-0.238593,-0.970931,0.002618,-0.125802,0.457001,...,-0.245113,-0.667758,0.353527,0.044640,-0.381576,0.176692,-0.082303,-0.071712,1.98,0
215427,140064.0,2.230376,-0.419655,-2.355074,-1.112343,0.654156,-0.199970,-0.192354,-0.204509,-0.947829,...,-0.041305,-0.092098,0.034395,-0.406038,0.165579,-0.271567,-0.028233,-0.044798,25.00,0
270534,164127.0,2.047560,-0.413865,-0.652293,0.210492,-0.166620,0.263414,-0.660149,0.030498,1.164479,...,0.118141,0.571919,0.095325,0.114475,-0.132190,0.575435,-0.019336,-0.044912,11.50,0
279218,168717.0,0.372628,-2.796082,-1.225956,1.795157,-1.189449,0.311994,0.444682,-0.057593,0.638770,...,0.743872,0.421573,-0.613215,-0.381661,-0.400999,-0.640148,-0.099158,0.095560,812.00,0

In [12]:
new_data.value_counts('Class')

Class
0    492
1    492
Name: count, dtype: int64

In [13]:
new_data['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [14]:
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94016.873984,-0.016194,0.186750,-0.028719,0.051240,-0.033587,-0.067057,-0.032514,-0.014131,0.036563,...,-0.008155,-0.072730,-0.111332,0.014394,0.026862,0.016185,0.006455,0.002429,-0.000601,70.823699
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [15]:
X=new_data.drop(['Class'],axis=1)
y=new_data['Class']

In [16]:
print(X)
print(y)

            Time        V1        V2        V3        V4        V5        V6  \
4109      3742.0  1.296273 -0.602021  0.615666 -0.466158 -1.047252 -0.563438
258626  158744.0  2.011600 -0.185795 -1.029954  0.334180 -0.238593 -0.970931
215427  140064.0  2.230376 -0.419655 -2.355074 -1.112343  0.654156 -0.199970
270534  164127.0  2.047560 -0.413865 -0.652293  0.210492 -0.166620  0.263414
279218  168717.0  0.372628 -2.796082 -1.225956  1.795157 -1.189449  0.311994
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
4109   -0.783412 -0.051961  0.756842  ... -0.042650 -0.215915 -0.624529
258626  0.002618 -0.125802  0.457001  ... -0.292801 -0.245113 -0.667758
215427 -0.192354 -0.204509 -0.947829  ...  0.177600 -0.041305 -0.092098
270534 -0.660149  0.030498  1.164479  ... -0.074952  0.118141  0.571919
279218  0.444682 -0.057593  0.638770  ...  1.377945  0.743872  0.421573
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
4109    0.165192 -0.057929  0.063396 -0.488104 -0.017801  0.015398   44.50
258626  0.353527  0.044640 -0.381576  0.176692 -0.082303 -0.071712    1.98
215427  0.034395 -0.406038  0.165579 -0.271567 -0.028233 -0.044798   25.00
270534  0.095325  0.114475 -0.132190  0.575435 -0.019336 -0.044912   11.50
279218 -0.613215 -0.381661 -0.400999 -0.640148 -0.099158  0.095560  812.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]
4109      0
258626    0
215427    0
270534    0
279218    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=2)

In [19]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [20]:
y_test

247995    1
205872    0
39107     0
2826      0
15451     1
         ..
108258    1
12108     1
99506     1
74496     1
281157    0
Name: Class, Length: 197, dtype: int64

In [21]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [22]:
model.fit(X_train,y_train)

LogisticRegression()

In [23]:
from sklearn.metrics import accuracy_score

Accuracy on training data

In [24]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,y_train)
print(f'The accuracy score on traning data : {training_data_accuracy}')

The accuracy score on traning data : 0.9466327827191868

Accuracy on testing data

In [25]:
X_test_prediction=model.predict(X_test)
testing_data_accuracy=accuracy_score(X_test_prediction,y_test)
print(f"The Accuracy Score on Testing Data : {testing_data_accuracy} ")

The Accuracy Score on Testing Data : 0.949238578680203

In [26]:
model.score(X_test,y_test)

0.949238578680203

In [27]:
model.predict([[10,1.44904378114715,-1.17633882535966,0.913859832832795,-1.37566665499943,-1.97138316545323,-0.62915213889734,-1.4232356010359,0.0484558879088564,-1.72040839292037,1.62665905834133,1.1996439495421,-0.671439778462005,-0.513947152539479,-0.0950450453999549,0.230930409124119,0.0319674667862076,0.253414715863197,0.854343814324194,-0.221365413645481,-0.387226474431156,-0.00930189652490052,0.313894410791098,0.0277401580170247,0.500512287104917,0.25136735874921,-0.129477953726618,0.0428498709381461,0.0162532619375515,7.8]])

c:\Users\mcs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [28]:
model.predict([[32714,-0.819001281862461,-0.604499868918639,1.85754884752641,0.0234804842407815,0.538404265728554,0.317676732695204,-0.595995786701447,0.3235314000494,0.491921747731075,-0.735681358856353,-1.20867748205636,0.748892157084224,1.33252384214047,-0.850759778611926,0.0794971814443214,-0.576289948415324,0.320706338387612,-0.684674931553358,1.2014432907642,0.425435164947655,-0.0868129833732003,-0.205671966137892,0.0976890566096455,-0.66586725625736,-0.211536447788071,1.08822278323727,-0.0112826813724574,0.0330306185973876,40]])

c:\Users\mcs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [29]:
model.predict([[12,-2.7918547659339,-0.327770756658658,1.64175016056605,1.76747274389883,-0.136588446465306,0.80759646826532,-0.422911389711497,-1.90710747624096,0.755712908314791,1.1510869876677,0.844555470974377,0.7929439518176,0.370448092803246,-0.734975105820311,0.406795710431001,-0.303057623825763,-0.155868714793874,0.778265457041536,2.22186801373788,-1.58212204356551,1.15166304848789,0.222181966098225,1.02058620426601,0.0283166513238872,-0.232746324289105,-0.23555721754117,-0.16477751177654,-0.0301536365592253,58.8]])

c:\Users\mcs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1], dtype=int64)